# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Down the Road
email: e.azadvari98@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I used to keep lots of notebooks for each category of my mind. Now I like to have them here all together, a constantly changing  portrait of me, down the life roads. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://NooraAz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: noora_avi
github_username:  nooraaz

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"
teaser: /images/head.jpg
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true

footer:
  links:
    - label: "Twitter"
      icon: "fad fa-fw fa-twitter-square"
      url: "https://twitter.com/noora_avi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nooraaz"

author:
  name     : "Noora Azadvari"
  #avatar   : "/assets/images/bio-photo.jpg"
  bio      : "I'm a Ph.D. candidate in Bioenginnering at the University of Oregon. You can read more about me in about ans resume pages."
  location : "Eugene, OR"
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
